name: Code Coverage

on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Installing requirements
      run: pip install ".[dev]"
    - name: Cache hypothesis database
      uses: actions/cache@v4
      with:
        path: .hypothesis/examples
        key: hypothesis-${{ runner.os }}-py3.13-${{ hashFiles('tests/**/*.py') }}
        restore-keys: |
          hypothesis-${{ runner.os }}-py3.13-
          hypothesis-${{ runner.os }}-
    - name: Generate Coverage Report
      run: |
        python -m coverage run --source=pyplugin/ -m pytest
        python -m coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage.xml
