name: Code Coverage

on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Installing requirements
      run: pip install ".[dev]"
    - name: Generate Coverage Report
      run: |
        python -m coverage run --source=pyplugin/ -m pytest
        python -m coverage xml
    - name: Upload test results to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
