name: Pylint

on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Installing requirements
      run: pip install ".[dev]"
    - name: Analysing the code with pylint
      run: |
        python -m pylint --fail-under=9.5 pyplugin/ tests/
    - name: Analysing the code with black
      run: |
        python -m black --check pyplugin/ tests/
    - name: Ensuring docs can compile
      run: |
        python -m sphinx -T -E -b html -d _build/doctrees -D language=en docs docs/out/html
