name: Pytest

on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.9", "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Installing requirements
      run: pip install ".[dev]"
    - name: Download example database
      uses: dawidd6/action-download-artifact@v2
      with:
        name: hypothesis-example-db
        path: .hypothesis/examples
        if_no_artifact_found: warn
        workflow_conclusion: completed
    - name: Run tests with pytest
      run: python -m pytest -s tests/
    - name: Upload example database
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: hypothesis-example-db
        path: .hypothesis/examples
