name: Pytest

on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"
  pull_request:
    branches:
      - "main"
      - "[0-9]+.[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [ "3.9", "3.12", "3.13" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
    - name: Installing requirements
      run: pip install ".[dev]"
    - name: Cache hypothesis database
      uses: actions/cache@v4
      with:
        path: .hypothesis/examples
        key: hypothesis-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('tests/**/*.py') }}
        restore-keys: |
          hypothesis-${{ runner.os }}-py${{ matrix.python-version }}-
          hypothesis-${{ runner.os }}-
    - name: Run tests with pytest
      run: python -m pytest -s tests/
